---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgAkBVEgD4Le2QkKEBV/P3vBQD1PqmcIvBCOhUsqZCFafEjPm8Eb7k0WYyKWotcapv+WSNCuO/qkyODeEWSLQ5yhJMyj1gm+zpGqFYwxRrE8G3jekPwZERmoob4uLKt/+8GsmFqbsWEgCQcYmecIS21gh7Q4ffyeXzmVz8M8fqfaqsaOtxSqn/89mMCdZfJVOP9xZeCnMg4gKJEF5YHWaiilGvKzV5+fw0pUt51qeU9vemKPsek86ldQSlYnrtAidSq39eZFIF49jIDOw5Ra7DDVcEsoL8ZL5OiWA08RulT8uWnoPCV+I+hMEpGmkB2iHskeryuPap/TBEgJw1muFD2E/X4Uqncedpt6ChnYaR63zqP+iD1YohNKjwcReo7Nhm268I30ITZqrjIVJ7hI4pa32Tqkz+9jJIwzv85Vr7vx5gIrnxb4EoJaKbsBkORMLxjz6w88wGI290/MGWYv+5LI3esZip4m560bhztR5T5NkC+Okj6GMV/pE02ceq4mHLm4YxVZ3O3fxRu2jwhNIOckw9VkbBXEpVwk7Yn05eC/FCkSNErf3W5JPtPWnjc+hWJaiYOcM2jQ45JdM/0X2uStCpCtFtedoBZYycyAp0IomYuCJwwwx1DOjJZDZVPgRzvjErz+WFIhCRcSpEZuKI+Lk50WBibnlDJX/nf+BdylBWSnsedwRBBbLkjeRtb7PrigBw2n+tFvF4EpCRO4RTl0RCs6Rq6NmcQO+rfcoLayx4iwZN102sMkWuCdop/t8now4CH7xIz4KjJf+sy37hMDoAUDYhTrO2A6gqUuYOZkWxqHZO46BqZX0zsgrN30ebXm6fgapEpqXEfrKXVvMpBycyB7OjDS/tOiZ7rjU1VWMpdAgnie29t/JlLLvi+MPFe+B/2+t6QN0fsHaA6tx0yT
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: regcred
    type: kubernetes.io/dockerconfigjson
